test change

diff --git a/.github/workflows/test.yaml b/.github/workflows/test.yaml
--- a/.github/workflows/test.yaml
+++ b/.github/workflows/test.yaml
@@ -38,5 +38,8 @@ jobs:
         echo "checking the test log:"
         cat log.txt
         errors=$(cat log.txt | grep "^Error")
-        if [ -n "$errors" ]; then echo $errors && exit 1; fi
-    
+        if [ -n "$errors" ]
+          echo "errors found: "
+          then echo $errors
+          exit 1
+        fi
